# Generated by Django 5.0.9 on 2026-08-28 12:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aggregator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Machine identifier, e.g. 'pairgate', 'vtung'",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human name, e.g. 'Pairgate'", max_length=100
                    ),
                ),
                ("base_url", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused (temporary)"),
                            ("disabled", "Disabled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "ledger_account_code",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'aggregator_float:pairgate' — must exist in ledger",
                        max_length=100,
                    ),
                ),
                (
                    "low_balance_alert_naira",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000,
                        help_text="Alert when our float drops below this",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "aggregators_aggregator",
            },
        ),
        migrations.CreateModel(
            name="AggregatorHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("closed", "Closed (healthy)"),
                            ("open", "Open (failing — traffic diverted)"),
                            ("half_open", "Half-open (probing recovery)"),
                        ],
                        db_index=True,
                        default="closed",
                        max_length=20,
                    ),
                ),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("consecutive_successes", models.IntegerField(default=0)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                (
                    "open_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="When circuit auto-transitions to half-open",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aggregator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health",
                        to="aggregators.aggregator",
                    ),
                ),
            ],
            options={
                "db_table": "aggregators_health",
            },
        ),
        migrations.CreateModel(
            name="AggregatorRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=100, help_text="Lower = tried first"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "aggregator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="aggregators.aggregator",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="services.servicevariation",
                    ),
                ),
            ],
            options={
                "db_table": "aggregators_route",
                "ordering": ["priority"],
                "indexes": [
                    models.Index(
                        fields=["variation", "priority", "is_active"],
                        name="aggregators_variati_2c51d9_idx",
                    )
                ],
                "unique_together": {("variation", "aggregator")},
            },
        ),
        migrations.CreateModel(
            name="AggregatorSKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aggregator_sku_code", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "aggregator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="aggregators.aggregator",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregator_skus",
                        to="services.servicevariation",
                    ),
                ),
            ],
            options={
                "db_table": "aggregators_sku",
                "indexes": [
                    models.Index(
                        fields=["aggregator", "variation", "is_active"],
                        name="aggregators_aggrega_0648d5_idx",
                    )
                ],
                "unique_together": {("aggregator", "variation")},
            },
        ),
    ]
