# Generated by Django 5.0.9 on 2026-08-28 12:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("monnify", "Monnify"),
                            ("paystack", "Paystack"),
                            ("flutterwave", "Flutterwave"),
                        ],
                        default="monnify",
                        max_length=20,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("account_name", models.CharField(max_length=200)),
                ("provider_reference", models.CharField(db_index=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_virtual_account",
            },
        ),
        migrations.CreateModel(
            name="WebhookInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("monnify", "Monnify"),
                            ("paystack", "Paystack"),
                            ("flutterwave", "Flutterwave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_id", models.CharField(db_index=True, max_length=200)),
                ("signature_verified", models.BooleanField(default=False)),
                ("payload", models.JSONField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True)),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "payments_webhook_inbox",
                "indexes": [
                    models.Index(
                        fields=["provider", "-received_at"],
                        name="payments_we_provide_38e48e_idx",
                    )
                ],
                "unique_together": {("provider", "event_id")},
            },
        ),
        migrations.CreateModel(
            name="FundingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("monnify", "Monnify"),
                            ("paystack", "Paystack"),
                            ("flutterwave", "Flutterwave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_reference", models.CharField(db_index=True, max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("applied", "Applied to wallet"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ledger_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funding_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_funding_event",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="payments_fu_user_id_0e51d7_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="payments_fu_status_67c072_idx",
                    ),
                ],
                "unique_together": {("provider", "provider_reference")},
            },
        ),
    ]
