# Generated by Django 5.0.9 on 2026-08-24 06:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("user_wallet", "User Wallet"),
                            ("platform_revenue", "Platform Revenue"),
                            ("aggregator_float", "Aggregator Float"),
                            ("refund_pool", "Refund Pool"),
                            ("promotional_credit", "Promotional Credit"),
                            (
                                "reseller_commission_payable",
                                "Reseller Commission Payable",
                            ),
                            ("pending_settlement", "Pending Settlement"),
                            ("platform_expense", "Platform Expense"),
                            ("suspense", "Suspense"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ledger_account",
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "journal_type",
                    models.CharField(
                        choices=[
                            ("funding", "Wallet Funding"),
                            ("purchase", "Service Purchase"),
                            ("refund", "Refund"),
                            ("commission", "Reseller Commission"),
                            ("reversal", "Manual Reversal"),
                            ("adjustment", "Manual Adjustment"),
                            ("payout", "Commission Payout"),
                            ("fee", "Platform Fee"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="ledger.journal",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_journal",
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="ledger.account",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="ledger.journal",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_entry",
            },
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_type", "is_active"],
                name="ledger_acco_account_4887c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["owner"], name="ledger_acco_owner_i_c86101_idx"),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["-created_at"], name="ledger_jour_created_56d660_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journal",
            unique_together={("journal_type", "reference")},
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["account", "-created_at"], name="ledger_entr_account_17836d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["journal"], name="ledger_entr_journal_c4e536_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                check=models.Q(("amount", 0), _negated=True),
                name="ledger_entry_amount_nonzero",
            ),
        ),
    ]
