# Generated by Django 5.0.9 on 2026-08-28 12:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("airtime", "Airtime"),
                            ("data", "Data"),
                            ("cable_tv", "Cable TV"),
                            ("electricity", "Electricity"),
                            ("education", "Education Pins"),
                            ("betting", "Betting"),
                            ("broadband", "Broadband"),
                            ("bulk_sms", "Bulk SMS"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("mtn", "MTN"),
                            ("glo", "Glo"),
                            ("airtel", "Airtel"),
                            ("9mobile", "9mobile"),
                            ("dstv", "DStv"),
                            ("gotv", "GOtv"),
                            ("startimes", "StarTimes"),
                            ("showmax", "Showmax"),
                            ("ikedc", "Ikeja Electric"),
                            ("ekedc", "Eko Electric"),
                            ("ibedc", "Ibadan Electric"),
                            ("aedc", "Abuja Electric"),
                            ("phedc", "Port Harcourt Electric"),
                            ("kedco", "Kano Electric"),
                            ("kaedco", "Kaduna Electric"),
                            ("jedc", "Jos Electric"),
                            ("eedc", "Enugu Electric"),
                            ("bedc", "Benin Electric"),
                            ("yedc", "Yola Electric"),
                            ("aedc-a", "Aba Electric"),
                            ("bet9ja", "Bet9ja"),
                            ("1xbet", "1xBet"),
                            ("sportybet", "SportyBet"),
                            ("betking", "BetKing"),
                            ("nairabet", "NairaBet"),
                            ("waec", "WAEC"),
                            ("neco", "NECO"),
                            ("jamb", "JAMB"),
                            ("nabteb", "NABTEB"),
                            ("smile", "Smile"),
                            ("spectranet", "Spectranet"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("icon", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "services_service",
                "ordering": ["category", "display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "network", "is_active"],
                        name="services_se_categor_773b5b_idx",
                    )
                ],
                "unique_together": {("category", "network", "name")},
            },
        ),
        migrations.CreateModel(
            name="ServiceVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'MTN 1GB SME 7-day'", max_length=200
                    ),
                ),
                (
                    "variation_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Price"),
                            ("variable_amount", "Variable Amount (user chooses)"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                ("variation_code", models.CharField(db_index=True, max_length=100)),
                (
                    "face_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("validity_days", models.IntegerField(blank=True, null=True)),
                ("data_mb", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "db_table": "services_variation",
                "ordering": ["service", "display_order", "face_value"],
            },
        ),
        migrations.CreateModel(
            name="TieredPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "user_tier",
                    models.CharField(
                        choices=[
                            ("regular", "Regular User"),
                            ("bronze", "Bronze Reseller"),
                            ("silver", "Silver Reseller"),
                            ("gold", "Gold Reseller"),
                            ("platinum", "Platinum Reseller"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="services.servicevariation",
                    ),
                ),
            ],
            options={
                "db_table": "services_tiered_pricing",
            },
        ),
        migrations.AddIndex(
            model_name="servicevariation",
            index=models.Index(
                fields=["service", "is_active"], name="services_va_service_e9b16c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicevariation",
            index=models.Index(
                fields=["variation_code"], name="services_va_variati_60c1fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tieredpricing",
            index=models.Index(
                fields=["variation", "user_tier", "is_active"],
                name="services_ti_variati_403e21_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tieredpricing",
            unique_together={("variation", "user_tier")},
        ),
    ]
