# Generated by Django 5.0.9 on 2026-08-24 06:42

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="Nigerian phone number in +234XXXXXXXXXX format",
                        max_length=15,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        help_text="Optional but recommended for free OTP & recovery",
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("phone_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "kyc_tier",
                    models.IntegerField(
                        choices=[
                            (0, "Unverified"),
                            (1, "Basic (Email)"),
                            (2, "Intermediate (NIN)"),
                            (3, "Full (BVN)"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("nin_verified_at", models.DateTimeField(blank=True, null=True)),
                ("bvn_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("regular", "Regular User"),
                            ("bronze", "Bronze Reseller"),
                            ("silver", "Silver Reseller"),
                            ("gold", "Gold Reseller"),
                            ("platinum", "Platinum Reseller"),
                        ],
                        db_index=True,
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("tier_upgraded_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_pin_hash", models.CharField(blank=True, max_length=255)),
                ("pin_attempts", models.IntegerField(default=0)),
                ("pin_locked_until", models.DateTimeField(blank=True, null=True)),
                ("prefer_whatsapp_otp", models.BooleanField(default=False)),
                ("whatsapp_opted_in", models.BooleanField(default=False)),
                ("telegram_chat_id", models.CharField(blank=True, max_length=64)),
                (
                    "referral_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=12, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "auth_user",
                "indexes": [
                    models.Index(
                        fields=["kyc_tier", "tier"], name="auth_user_kyc_tie_f37201_idx"
                    ),
                    models.Index(
                        fields=["date_joined"], name="auth_user_date_jo_f1a394_idx"
                    ),
                ],
            },
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
    ]
