# Generated by Django 5.0.9 on 2026-08-28 12:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aggregators", "0001_initial"),
        ("ledger", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("airtime", "Airtime"),
                            ("data", "Data"),
                            ("cable_tv", "Cable TV"),
                            ("electricity", "Electricity"),
                            ("education", "Education Pin"),
                            ("betting", "Betting"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Phone / meter / smartcard / etc.", max_length=100
                    ),
                ),
                (
                    "recipient_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Any extra fields (meter_type, customer_name)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Face value the user 'bought'",
                        max_digits=12,
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What we charged the user",
                        max_digits=12,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What we paid the aggregator",
                        max_digits=12,
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="sale_price - cost_price",
                        max_digits=12,
                    ),
                ),
                ("idempotency_key", models.CharField(db_index=True, max_length=100)),
                (
                    "aggregator_reference",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("aggregator_response", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_message", models.CharField(blank=True, max_length=500)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("processing_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_attempts", models.IntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "aggregator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="aggregators.aggregator",
                    ),
                ),
                (
                    "debit_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journal",
                    ),
                ),
                (
                    "refund_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="services.servicevariation",
                    ),
                ),
            ],
            options={
                "db_table": "transactions_transaction",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="transaction_user_id_386a11_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="transaction_status_d2f80b_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "-created_at"],
                        name="transaction_transac_20ac5e_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"), name="tx_user_idempotency_unique"
            ),
        ),
    ]
